### ISSUE TITLE
tech stack discussion

### ISSUE THREAD

**Issue by CubeyTheCube** [screech-org/www#3]
svelte bad

**Comment by lankybox02** [comment]
+1

**Comment by Chiroyce1** [comment]
it isnt bad but can be buggy - so nextJS is another choice?

**Comment by Chiroyce1** [comment]
What about Vue? It won't be React based and also not buggy (it's at v2+ and svelte is v<1.0)

**Comment by Looky1173** [comment]
> We don't want to copy scratch's react side of things as well.
We should not choose a tech stack to be different, we should choose one to be efficient. Nextjs is a great framework that would be a perfectly valid choice for Screech, no matter if Scratch uses it or not.

**Comment by CubeyTheCube** [comment]
best solution: we fork scratch-www, we can port it to next if we want but we don't really need to

**Comment by kccuber-scratch** [comment]
> which is why it'd be best just to fork scratch-www

Which also uses frontend frameworks and is part of the "javascript ecosystem."

**Comment by CubeyTheCube** [comment]
> > which is why it'd be best just to fork scratch-www
> 
> Which also uses frontend frameworks and is part of the "javascript ecosystem."

I already explained how just forking scratch-www is the least work and therefore the "least bad" solution.

**Comment by CubeyTheCube** [comment]
For the API, are we sure we want to use Fastify and Mongo? It'd probably be a smarter choice to use a relational database (Scratch uses MySQL, we could possibly use Postgres), and express rather than Fastify, since it doesn't really matter altogether what we use and express would probably be the best choice.

**Comment by Weredime** [comment]
Everyone wants express so I guess we could add websocket polling?

**Comment by Weredime** [comment]
> Postgres

or Supabase

**Comment by micahlt** [comment]
> For the API, are we sure we want to use Fastify and Mongo? It'd probably be a smarter choice to use a relational database (Scratch uses MySQL, we could possibly use Postgres), and express rather than Fastify, since it doesn't really matter altogether what we use and express would probably be the best choice.

I really doubt we'll be able to scale Express to the extent that we'd need to for this project.

> API built-in to Next.js?

This.  Serverless is a really affordable way to deal with data, and for something like a Scratch clone I think it's perfect.

> I already explained how just forking scratch-www is the least work and therefore the "least bad" solution.

I don't know if you've looked at the scratch-www codebase, but it's _really_ complex.  Personally I think that's a bad idea, because nobody really knows how all of the code works together - especially since a large portion of the existing site is still on scratchr2).

**Comment by Oren-Lindsey** [comment]
_Please_ do sveltekit, its so much better. Definitely don't do react or next.js. Do something serverless, its hard to scale a normal server to the extent we need
Also don't just fork `scratch-www`, that feels like cheating. We're here to make a better version of scratch, not copy it
For the db, I think mongo is best because its the simplest, but mysql is probably an ok option

**Comment by Weredime** [comment]
> _Please_ do sveltekit, its so much better. Definitely don't do react or next.js. Do something serverless, its hard to scale a normal server to the extent we need Also don't just fork `scratch-www`, that feels like cheating. We're here to make a better version of scratch, not copy it For the db, I think mongo is best because its the simplest, but mysql is probably an ok option

its kinda strange in the position im in:

i want to do sveltekit like you
everybody else wants next.js
its a community project and you guys decide what happens anyway

**Comment by Looky1173** [comment]
> Please do sveltekit, its so much better.Please do sveltekit, its so much better.

@Oren-Lindsey In what ways is SvelteKit so much better? It is a relatively new framework while Nextjs has been tested and proven itself in production thousands of times.

**Comment by Oren-Lindsey** [comment]
> > Please do sveltekit, its so much better.Please do sveltekit, its so much better.

> @Oren-Lindsey In what ways is SvelteKit so much better? It is a relatively new framework while Nextjs has been tested and proven itself in production thousands of times.

Sveltekit is soooo much dang easier to code and it's faster loading pages and running endpoints.
I don't really care about it being new as long as it works. I have seen numerous sveltekit apps in prod and they all work very well

**Comment by micahlt** [comment]
> Sveltekit is soooo much dang easier to code

By which you mean not having access to the `window` object?  Yeah, really easy lol

> I don't really care about it being new as long as it works.

You should care!  The support and the ecosystem are critical.  I've encountered numerous bugs in SvelteKit that are not even being worked on because the community is too small.

**Comment by CubeyTheCube** [comment]
> I don't know if you've looked at the scratch-www codebase, but it's _really_ complex. Personally I think that's a bad idea, because nobody really knows how all of the code works together - especially since a large portion of the existing site is still on scratchr2).
Yes, I have, and I'm not sure what you mean. It's pretty straightforward.

**Comment by Chiroyce1** [comment]
> It's much, much easier to improve something than to rewrite it.

but i think it's better to rewrite it since then we'll be sure to have full control and understand how exactly all the pages/components work

**Comment by micahlt** [comment]
> > It's much, much easier to improve something than to rewrite it.
> 
> but i think it's better to rewrite it since then we'll be sure to have full control and understand how exactly all the pages/components work

I definitely agree with this.  Perhaps we should put this to a community vote?

**Comment by Oren-Lindsey** [comment]
I think at least we definitely __shouldn't__ use react or nextjs
React straight up sucks, we should at least use vue, nuxt, or svelte

**Comment by micahlt** [comment]
> I think at least we definitely __shouldn't__ use react or nextjs
> React straight up sucks, we should at least use vue, nuxt, or svelte

Vue is definitely more approachable than React, I can agree with you on that.  Their ecosystems are of comparable sizes.

**Comment by Weredime** [comment]
> > > It's much, much easier to improve something than to rewrite it.
> > 
> > 
> > but i think it's better to rewrite it since then we'll be sure to have full control and understand how exactly all the pages/components work
> 
> I definitely agree with this. Perhaps we should put this to a community vote?

scroll up to the reaction vote

**Comment by Chiroyce1** [comment]
@Weredime I made a better poll here - https://github.com/screech-org/www/discussions/9

**Comment by Weredime** [comment]
Ok

**Comment by CubeyTheCube** [comment]
Note that if we use React we don't need to use Next, in fact Scratch doesn't use Next

**Comment by Weredime** [comment]
guys like I don't think it's going to work out -- nobody's coding anything (except me probably) and me as a person hates react and loves svelte

@cubeythecube this is better scratch, not scratch

**Comment by CubeyTheCube** [comment]
better scratch means improving on scratch, not necessarily recreating it

> nobody's coding anything 

this project's always been doomed to die

**Comment by kccuber-scratch** [comment]
look can we stop with the pessimistic attitude. with that attitude this project is going to go nowhere.

**Comment by Weredime** [comment]
I personally don't feel like Next has to happen - Svelte is fine and fits our needs at the present time - We could migrate when we need to
